name: CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - feature/terraform-ci

jobs:
  cd:
    uses: lbasg-lab/cicd-pipelines/.github/workflows/cd.yml@feature/terraform-ci
    with:
      config: .cicd-config.yml
    secrets:
      HCP_TERRAFORM_TOKEN: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      